name: build and test

on: [push]

jobs:
    build-Ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: build and run
              run: |
                  mkdir build
                  cd build
                  cmake .. -DIMPLICIT_PREDICATES_UNIT_TESTS=On -DCMAKE_BUILD_TYPE=Release
                  cmake --build . --config Release -j
                  cmake --build . --target test
            - name: benchmark
              run: |
                  cd build
                  ./implicit_predicates_tests benchmark
